<?
include 'connect.php';
include 'funkcijas.php';
include '../check_login.php';
include 'menu.php';
if ($mlietotajs['g_report']!='Y') return;

menu('faila_ielasisana',$valoda);

//set_time_limit(0); 

function valideet($tag,$content)
{
	$content = ' '.$content;
	$start_tag = strpos($content,"<".$tag.">");
	$end_tag = strpos($content,"</".$tag.">");
	if ($start_tag and $end_tag)
	{
		$value = substr($content,($start_tag + strlen($tag) + 2),$end_tag - ($start_tag + strlen($tag) + 2));
		if ($tag == 'nr') $value = str_replace("/","_",$value);
	}
	return $value;
}

// ja padots id tad ņem no datubāzes postu
/*
  VMF data internet transmission module
	version: v1.0.0
  Created by Gunars Rodins (uwix@inbox.lv) (c) 2005

  @params:   Get data by POST method,in fields:
	SIGNATURE - digest of trasmission, generated by formula:
	            =sha1(DEVICE|SENDER|PRESHAREDSECRET|DIGEST);
	DEVICE - identity of sending device
	SENDER - identity of user - login number, which sends info (user can send only after log-in)
	DIGEST - sha1 digest of data
	CNT - content of file

	@note: PRESHAREDSECRET ($transkey variable) - password, same in sender and receiver part. See config file of Symbol.

	@return: validation results in plain text (not HTML formated), shortened to fit on Symbol screen.
*/

$name = $_FILES['fails']['name'];
echo 'Sāk faila ' . $name . ' ielasīšanu<BR /><BR />';
$fsk=copy($_FILES['fails']['tmp_name'],'../batch/'.$name );
chdir('../batch');
$file_array = file($name,NULL);
$file_text = $file_array[0];
chdir('..');
print_vars();

function print_vars()
{
				global $file_text;
				
				$content = strtolower(valideet("vmffile",$file_text));
        $content = iconv("cp1257","UTF-8",$content);
				$type = strtolower(valideet("type",$content));
				
				if ($type == 'pm')
				{
	
					$pm = valideet("pm",$content);
					$pm = ' '.$pm;
					
					$nr = valideet("nr",$pm);
					if ($nr == '') $nr = 'NULL';
					$me = valideet("me",$pm);
					if ($me == '') $me = 'NULL';
					$so = valideet("so",$pm);
					if ($so == '') $so = 'NULL';
					$sg = valideet("sg",$pm);
					if ($sg == '') $sg = 'NULL';
					$pk = valideet("pk",$pm);
					if ($pk == '') $pk = 'NULL';
					$rn = valideet("rn",$pm);
					if ($rn == '') $rn = 'NULL';
					$ps = valideet("ps",$pm);
					$pz = valideet("pz",$pm);
					$sf = valideet("sf",$pm);
					$fs = valideet("fs",$pm);
					$ag = valideet("ag",$pm);
					if ($ag == '') $ag = 'NULL';
					$gr = valideet("gr",$pm);
					if ($gr == '') $gr = 'NULL';
					$pl = valideet("pl",$pm);
					if ($pl == '') $pl = 'NULL';
					$ti = valideet("ti",$pm);
					if ($ti == '') $ti = 'NULL';
					$bk = valideet("bk",$pm);
					if ($bk == '') $bk = 'NULL';
					$bp = valideet("bp",$pm);
					if ($bp == '') $bp = 'NULL';
					$sk1 = valideet("sk1",$pm);
					if ($sk1 == '') $sk1 = 'NULL';
					$si1 = valideet("si1",$pm);
					if ($si1 == '') $si1 = 'NULL';
					$sk2 = valideet("sk2",$pm);
					if ($sk2 == '') $sk2 = 'NULL';
					$si2 = valideet("si2",$pm);
					if ($si2 == '') $si2 = 'NULL';
					$sk3 = valideet("sk3",$pm);
					if ($sk3 == '') $sk3 = 'NULL';
					$si3 = valideet("si3",$pm);
					if ($si3 == '') $si3 = 'NULL';
					$ts = valideet("ts",$pm);
					if ($ts == '') $ts = 'NULL';
					$te = valideet("te",$pm);
					if ($te == '') $te = 'NULL';

					
					mysql_query("INSERT INTO `papirmalka` (`nr`, `me`, `so`, `sg`, `pk`, `rn`, `ps`, `pz`, `sf`, `fs`, `ag`, `gr`, `pl`, `ti`, `bk`, `bp`, `sk1`, `si1`, `sk2`, `si2`, `sk3`, `si3`, `ts`, `te`) VALUES ('".$nr."', $me, '".$so."', '".$sg."', '".$pk."', '".$rn."','".$ps."','".$pz."','".$sf."','".$fs."', $ag, $gr, $pl, $ti, $bk, $bp, $sk1, $si1, $sk2, $si2, $sk3, $si3, '".$ts."', '".$te."')");
//echo "INSERT INTO `papirmalka` (`nr`, `me`, `so`, `sg`, `pk`, `rn`, `ps`, `pz`, `sf`, `fs`, `ag`, `gr`, `pl`, `ti`, `bk`, `bp`, `sk1`, `si1`, `sk2`, `si2`, `sk3`, `si3`, `ts`, `te`) VALUES ('".$nr."', $me, '".$so."', '".$sg."', '".$pk."', '".$rn."','".$ps."','".$pz."','".$sf."','".$fs."', $ag, $gr, $pl, $ti, $bk, $bp, $sk1, $si1, $sk2, $si2, $sk3, $si3, '".$ts."', '".$te."')";
					//mysql_query(" INSERT INTO test nr,me,so,sg,pk,rn,ag,gr,pl,ti,bk,bp,sk1,si1,sk2,si2,sk3,si3,ts,te) VALUES $nr,$me,$so,$sg,$pk,$rn,$ag,$gr,$pl,$ti,$bk,$bp,$sk1,$si1,$sk2,$si2,$sk3,$si3,'".$ts."','".$te."') ");
					//echo " INSERT INTO `test` (`nr`, `me`, `so`, `sg`, `pk`, `rn`, `ag`, `gr`, `pl`, `ti`, `bk`, `bp`, `sk1`, `si1`, `sk2`, `si2`, `sk3`, `si3`, `ts`, `te`) VALUES ('".$nr."', $me, $so, $sg, $pk, $rn, $ag, $gr, $pl, $ti, $bk, $bp, $sk1, $si1, $sk2, $si2, $sk3, $si3, '".$ts."', '".$te."') ";

					$test_id = mysql_insert_id();

					$iu = explode("</iu>",$pm);
					for ($i=0;$i<count($iu)-1;$i++)
					{
						$sx = valideet("sx",$iu[$i]);
						if ($sx == '') $sx = 'NULL';
						$kx = valideet("kx",$iu[$i]);
						if ($kx == '') $kx = 'NULL';
						$bx = valideet("bx",$iu[$i]);
						if ($bx == '') $bx = 'NULL';
						$d1 = valideet("d1",$iu[$i]);
						if ($d1 == '') $d1 = 'NULL';
						$lx = valideet("lx",$iu[$i]);
						if ($lx == '') $lx = 'NULL';
						$d2 = valideet("d2",$iu[$i]);
						if ($d2 == '') $d2 = 'NULL';
						$rx = valideet("rx",$iu[$i]);
						if ($rx == '') $rx = 'NULL';
						$re = valideet("re",$iu[$i]);
						if ($re == '') $re = 'NULL';
						$kb = valideet("kb",$iu[$i]);
						if ($kb == '') $kb = 'NULL';
						$anuled = valideet("anuled",$iu[$i]);
						if ($anuled == '') $anuled = 'NULL';

						mysql_query("INSERT INTO `papirmalka_merijumi` (`papirmalka_id`, `papirmalka_nr`,  `sx`, `kx`, `bx`, `dl`, `lx`, `d2`, `rx`, `re`, `kb`, `anuled`) VALUES ($test_id, '".$test_nr."', $sx, $kx, $bx, $d1, $lx, $d2, $rx, $re, '".$kb."', $anuled)");
						//echo "INSERT INTO `papirmalka_merijumi` (`test_id`, `sx`, `kx`, `bx`, `dl`, `lx`, `d2`, `rx`, `re`, `kb`, `anuled`) VALUES ($test_id, $sx, $kx, $bx, $d1, $lx, $d2, $rx, $re, '".$kb."', $anuled)";
					}
					//*********** excel faila izveide ************************
					mysql_query ("INSERT INTO `zagbalki_merijumi` ( `zagbalki_id` , `zagbalki_pasnr` , `nr` , `pg` , `sg` , `mt` , `tc` , `gr` , `rg` , `rc` , `sk` , `im` , `pi` , `ts` , `te` , `kb` ) VALUES ('".$test_id."', '".$pasnr."', '".$nr."', '".$pg."', '".$sg."', '".$mt."', '".$tc."', '".$gr."', '".$rg."', '".$rc."', '".$sk."', '".$im."', '".$pi."', '".$ts."', '".$te."', '".$kb."')");

					$myFile = "pocket_pc/documents/".$nr."pm.dat";
					$fh = fopen($myFile, 'w') or die("can't open file");

					$stringData = $content;
					fwrite($fh, $stringData);

					//$stringData = "tesT teST\n";
					//fwrite($fh, $stringData);
					fclose($fh); 
					echo 'Papīrmalkas fails ' . $name . ' ir ielasīts veiksmīgi!';

				}


//**********************************************Zāģbāļku ielasīšana strādā!**************************************************************************************************

				
				if ($type == 'zb')
				{

					$header = valideet("header",$content);
          echo "Saturs = ".$content.'<br />';
					$pasutitajs  = valideet("pasutitajs",$content);
					if ($pasutitajs == '') $pasutitajs = 'NULL';
					$piegadatajs  = valideet("piegadatajs",$content);
					if ($piegadatajs == '') $piegadatajs = 'NULL';
					$viet_kods = valideet("viet_kods",$header);
					if ($viet_kods == '') $viet_kods = 'NULL';
					$kontrolmernieks = valideet("kontrolmernieks",$header);
					if ($kontrolmernieks == '') $kontrolmernieks = 'NULL';
					$pasnr = valideet("pasnr",$header);
					if ($pasnr == '') $pasnr = 'NULL';
					$pas_nos = valideet("pas_nos",$header);
					if ($pas_nos == '') $pas_nos = 'NULL';
					$started = valideet("started",$header);
					if ($started == '') $started = 'NULL';

					mysql_query("INSERT INTO `zagbalki` (`pasutitajs`, `piegadatajs`,`viet_kods`, `kontrolmernieks`, `pasnr`, `pas_nos`, `started`) VALUES ('".$pasutitajs."', '".$piegadatajs."', '".$viet_kods."', '".$kontrolmernieks."', '".$pasnr."', '".$pas_nos."', '".$started."')");

					$test_id = mysql_insert_id();
          
					$zb = explode("</zb>",$file_text);
//					print_r($zb);
					
					for ($i=0;$i<count($zb)-1;$i++)
					{
						$nr = valideet("nr",$zb[$i]);
						if ($nr == '') $nr = 'NULL';
						$pg = valideet("pg",$zb[$i]);
						if ($pg == '') $pg = 'NULL';
						$sg = valideet("sg",$zb[$i]);
						if ($sg == '') $sg = 'NULL';
						$mt = valideet("mt",$zb[$i]);
						if ($mt == '') $mt = 'NULL';
						$tc = valideet("tc",$zb[$i]);
						if ($tc == '') $tc = 'NULL';
						$vc = valideet("vc",$zb[$i]);
						if ($vc == '') $vc = 'NULL';
						$rcc = valideet("rcc",$zb[$i]);
						if ($rcc == '') $rcc = 'NULL';
						$gr = valideet("gr",$zb[$i]);
						if ($gr == '') $gr = 'NULL';
						$rg = valideet("rg",$zb[$i]);
						if ($rg == '') $rg = 'NULL';
						$rc = valideet("rc",$zb[$i]);
						if ($rc == '') $rc = 'NULL';
						$sk = valideet("sk",$zb[$i]);
						if ($sk == '') $sk = 'NULL';
						$im = valideet("im",$zb[$i]);
						if ($im == '') $im = 'NULL';
						$pi = valideet("pi",$zb[$i]);
						if ($pi == '') $pi = 'NULL';
						$ts = valideet("ts",$zb[$i]);
						if ($ts == '') $ts = 'NULL';
						$te = valideet("te",$zb[$i]);
						if ($te == '') $te = 'NULL';
						$kb = valideet("kb",$zb[$i]);
						if ($kb == '') $kb = 'NULL';

						//*********** faila izveide ************************
						mysql_query ("INSERT INTO `zagbalki_merijumi` ( `zagbalki_id` , `zagbalki_pasnr` , `nr` , `pg` , `sg` , `mt` , `tc` , `vc` , `rcc` , `gr` , `rg` , `rc` , `sk` , `im` , `pi` , `ts` , `te` , `kb` ) VALUES ('".$test_id."', '".$pasnr."', '".$nr."', '".$pg."', '".$sg."', '".$mt."', '".$tc."', '".$vc."', '".$rcc."', '".$gr."', '".$rg."', '".$rc."', '".$sk."', '".$im."', '".$pi."', '".$ts."', '".$te."', '".$kb."')");

						$myFile = "pocket_pc/documents/".$pasnr."zb.dat";
						
						$fh = fopen($myFile, 'w') or die("can't open file");

						$stringData = $file_text;
						fwrite($fh, $stringData);

						//$stringData = "tesT teST\n";
						//fwrite($fh, $stringData);
						fclose($fh); 
					}

//					die("Hello World!");

					echo 'Zāģbaļķu fails ' . $name . ' ir ielasīts veiksmīgi!';

				}

//************************************************************************************************************************************************



				if ($type == 'zbm')
				{
					$header = valideet("header",$content);

					$pasutitajs  = valideet("pasutitajs",$header);
					$viet_kods = valideet("viet_kods",$header);
					$kontrolmernieks = valideet("kontrolmernieks",$header);
					$pasnr = valideet("pasnr",$header);
					$tdu = valideet("tdu",$header);
					$pas_nos = valideet("pas_nos",$header);
					$pavaddok = valideet("pavaddok",$header);
					$autonr = valideet("autonr",$header);
					$piekabnr = valideet("piekabnr",$header);
					$metode = valideet("metode",$header);
					$sofer = valideet("sofer",$header);
					$me = valideet("me",$header);
//					$started = valideet("started",$content);
					$started = date("d.m.Y H.i.s");

					/*echo $pasutitajs."<br>";
					echo $viet_kods."<br>";
					echo $kontrolmernieks."<br>";
					echo $pasnr."<br>";
					echo $pas_nos."<br>";
					echo $started."<br>";*/
					
					mysql_query("INSERT INTO `fails_zbm` (`pasutitajs`, `viet_kods`, `kontrolmernieks`, `pasnr`, `pas_nos`, `pavaddok`, `transp_darba_uzd`, `autonr`, `piekabnr`, `sofer`, `metode` , `me`, `started`) VALUES ('".$pasutitajs."', '".$viet_kods."', '".$kontrolmernieks."', '".$pasnr."', '".$pas_nos."', '".$pavaddok."', '".$tdu."', '".$autonr."','".$piekabnr."','".$sofer."','".$metode."','".$me."','".$started."')");

					$new_id = mysql_insert_id();

					$iu = explode("</iu>",$content);
					echo count($iu);
					for ($i=0;$i<count($iu)-1;$i++)
					{
						$sg = valideet("sg",$iu[$i]);
						$tc = valideet("tc",$iu[$i]);
						$vc = valideet("vc",$iu[$i]);
						$rcc = valideet("rcc",$iu[$i]);
						$gr = valideet("gr",$iu[$i]);
						$rg = valideet("rg",$iu[$i]);
						$rc = valideet("rc",$iu[$i]);
						$sk2 = valideet("sk2",$iu[$i]);
						$sk = valideet("sk",$iu[$i]);
						$im = valideet("im",$iu[$i]);
						$im2 = valideet("im2",$iu[$i]);
						$pi = valideet("pi",$iu[$i]);
						$kb = valideet("kb",$iu[$i]);
						$ts = valideet("ts",$iu[$i]);
						$te = valideet("te",$iu[$i]);
						$anuled = valideet("anuled",$iu[$i]);

						/*echo "*********zb".$i."**************<br>";
						echo $nr."<br>";
						echo $pg."<br>";
						echo $sg."<br>";
						echo $mt."<br>";	
						echo $tc."<br>";
						echo $gr."<br>";
						echo $rg."<br>";
						echo $rc."<br>";
						echo $sk."<br>";
						echo $im."<br>";
						echo $pi."<br>";
						echo $ts."<br>";
						echo $te."<br>";
						echo $kb."<br>";
						echo "******** /zb".$i."*************<br>"; */
						
						//*********** faila izveide ************************
						mysql_query ("INSERT INTO `fails_zbm_ui` ( `fails_zbm_id` , `sg` , `tc` , `vc` , `rcc` , `gr` , `rg` , `rc` , `sk` , `sk2`, `im` , `im2`, `pi` , `kb` , `ts` , `te`, anuled ) VALUES ('".$new_id."', '".$sg."', '".$tc."', '".$vc."', '".$rcc."', '".$gr."', '".$rg."', '".$rc."', '".$sk."', '".$sk2."', '".$im."', '".$im2."', '".$pi."', '".$kb."', '".$ts."', '".$te."', '".$anuled."')");

						$myFile = "pocket_pc/documents/".$pasnr."zbm.dat";
						$fh = fopen($myFile, 'w') or die("can't open file");

						$stringData = $content;
						fwrite($fh, $stringData);

						//$stringData = "tesT teST\n";
						//fwrite($fh, $stringData);
						fclose($fh); 
					}

					echo 'Zāģbaļķu mērijumu fails ' . $name . ' ir ielasīts veiksmīgi!';

				}



				if ($type == 'kz')
				{
//					$header = valideet("header",$content);

					$darba_uzd_nr  = valideet("dunr",$content);
					$pasutitajs  = valideet("pasu",$content);
					$pavadzimes_datums_tmp  = valideet("pvddatums",$content);
					$piegadatajs  = valideet("pieg",$content);
					$sanemejs  = valideet("pasu",$content);
					$uzm_vieta  = valideet("viet",$content);
					$transports  = valideet("tran",$content);
					$soferis  = valideet("sofe",$content);
					$mernieks  = "99";
					
					$pavadzimes_datums = substr($pavadzimes_datums_tmp,-4)."-".substr($pavadzimes_datums_tmp,2,2)."-".substr($pavadzimes_datums_tmp,0,2)." 00:10:00";
					
          $ielasisanas_fatums = date("Y-m-d H:i:s");
					mysql_query("INSERT INTO `t_h_kraujmers` (`date_upload`, `date_pavadzime`, `darba_uzdevuma_num`, `uzm_vieta`, `buyer`, `seller`, `reciever`, `transport`, `driver`, `login_name`) VALUES ('".$ielasisanas_fatums."', '".$pavadzimes_datums."', '".$darba_uzd_nr."', '".$uzm_vieta."', '".$pasutitajs."', '".$piegadatajs."', '".$pasutitajs."', '".$transports."', '".$soferis."', '".$mernieks."')");

					$new_id = mysql_insert_id();

					$iu = explode("</gr>",$content);
					echo count($iu);
					for ($i=0;$i<count($iu)-1;$i++)
					{
						$gredas_numurs = valideet("grnr",$iu[$i]);
						$mernieks = valideet("me",$iu[$i]);
						$ts = valideet("ts",$iu[$i]);
						$te = valideet("te",$iu[$i]);
						$sortimenta_kods = valideet("sortk",$iu[$i]);
						$suga_1_kods = valideet("su1",$iu[$i]);
						$suga_1_proc = valideet("su1proc",$iu[$i]);
						$suga_2_kods = valideet("su2",$iu[$i]);
						$suga_2_proc = valideet("su2proc",$iu[$i]);
						$suga_3_kods = valideet("su3",$iu[$i]);
						$suga_3_proc = valideet("su3proc",$iu[$i]);
						$garums = valideet("l",$iu[$i]);
						$solis = valideet("step",$iu[$i]);
						$augstums_vid = valideet("havg",$iu[$i]);
						$augstums = valideet("hmes",$iu[$i]);
						$platums_vid = valideet("plavg",$iu[$i]);
						$platums = valideet("plmes",$iu[$i]);
						$tilp_koef = valideet("k",$iu[$i]);
						$braka_kods = valideet("bk",$iu[$i]);
						$braka_proc = valideet("bproc",$iu[$i]);
						$kb = valideet("kb",$iu[$i]);
						$anuled = valideet("anuled",$iu[$i]);
						$opcija = 'A';
						if($anuled == 1){$opcija = "D";}

						mysql_query("INSERT INTO `t_b_kraujmers` ( `ts` , `te` , `mernieks` , `t_h_id` , `gredas_numurs` , `sortimenta_kods` , `suga_1_kods` , `suga_1_proc` , `suga_2_kods` , `suga_2_proc` , `suga_3_kods` , `suga_3_proc` , `garums` , `solis`, `augstums_vid`, `augstums`, `platums_vid`, `platums`, `tilp_koef`, `braka_kods`, `braka_proc`, `kb`, `opcija`) VALUES ('".$ts."', '".$te."', '".$mernieks."', '".$new_id."', '".$gredas_numurs."', '".$sortimenta_kods."', '".$suga_1_kods."', '".$suga_1_proc."', '".$suga_2_kods."', '".$suga_2_proc."', '".$suga_3_kods."', '".$suga_3_proc."', '".$garums."', '".$solis."', '".$augstums_vid."', '".$augstums."', '".$platums_vid."', '".$platums."', '".$tilp_koef."', '".$braka_kods."', '".$braka_proc."', '".$kb."', '".$opcija."')");

						$myFile = "pocket_pc/documents/".$darba_uzd_nr."kz.dat";
						$fh = fopen($myFile, 'w') or die("can't open file");

						$stringData = $content;
						fwrite($fh, $stringData);

						fclose($fh); 
					}

					echo 'Kraujmēra fails ' . $name . ' ir ielasīts veiksmīgi!';

				}

				/********************************************
				*                                           *
				*                end                        *
				*                                           *
				*********************************************/
		 }


?>

<BR />
<BR />
<a href="transf_upload.php">
	Ielasīt vēl failu
</a>